import turtle
s = turtle.getscreen()
turtle.title("My Amazing Program")
franck_mini = turtle.Turtle()
me = turtle.Turtle()
style1 = ('Courier', 10, 'italic')
me.shape("circle")
me.hideturtle()
me.shapesize(0.5,0.5,0.5)
me.speed(10)
me.penup()
me.setposition(-250,200)
me.speed(1)
me.showturtle()
me.color("blue")
me.write("Hello, World", style1)
franck_mini.speed(1)
franck_mini.rt(720)
me.clear()
me.color("black")
me.write("Now the basics are over, hi humans! I am very excited to introduce you to my friend the art-y turtle!")
franck_mini.shapesize(1,1,1)
franck_mini.pensize(3)
franck_mini.pendown()
franck_mini.speed(1)
franck_mini.rt(3)
franck_mini.forward(100)
franck_mini.lt(186)
franck_mini.forward(200)
franck_mini.rt(180)
franck_mini.rt(3)
franck_mini.forward(100)
franck_mini.lt(186)
franck_mini.forward(200)
franck_mini.rt(180)
me.clear()
me.write("Wait what are you doing?!Turtle!")
franck_mini.circle(60)
franck_mini.rt(3)
franck_mini.forward(100)
franck_mini.lt(186)
franck_mini.forward(200)
franck_mini.rt(180)
franck_mini.shapesize(0.5,0.5,0.5)
franck_mini.rt(150)
franck_mini.pencolor("yellow")
me.clear()
me.color("red")
me.write("Why are you running away? Wait come back!", font=style1)
franck_mini.speed(1)
franck_mini.lt(50)
franck_mini.forward(200)
franck_mini.bk(200)
franck_mini.fd(200)
me.clear()
me.write("Hey come back!I just figured it out! Your an imposter turtle!", font=style1)
me.setposition(-250,180)
me.write(" Wait I have a word or two for you! Come back now!", font=style1)
franck_mini.hideturtle()
franck_mini.rt(90)
franck_mini.forward(100)
franck_mini.lt(90)
franck_mini.forward(50)
franck_mini.clear()
franck_mini.hideturtle()
#enter art-y turtle
franck_mini.shape("turtle")
franck_mini.fillcolor("#00cc66")
franck_mini.penup()
franck_mini.speed(1)
franck_mini.rt(720)
me.clear()
me.write("     :(", font=style1)
franck_mini.forward(100)
franck_mini.lt(720)
franck_mini.forward(200)
franck_mini.rt(180)
me.clear()
me.color("#1a8cff")
me.write("       :(", font=style1)
franck_mini.circle(60)
franck_mini.showturtle()
franck_mini.penup()
franck_mini.speed(1)
franck_mini.shapesize(2,2,2)
franck_mini.setposition(-400,0)
franck_mini.rt(90)
franck_mini.goto(0,0)
me.clear()
me.write("Hiiiii! It's my arty friend Frank Mini! I missed you!", font=style1)
me.clear()
franck_mini.rt(720)
me.write("That imposter was so rude, he didn't even say goodbye :(", font=style1)
me.left(180)
me.fd(20)
me.right(180)
me.fd(20)
me.left(180)
me.fd(20)
me.right(180)
me.fd(20)
me.clear()
me.shapesize(1,1,1)
me.color("deep pink")
me.write(" You are here now! Party! I'll let you work your magic!", font=style1)
franck_mini.left(90)
franck_mini.fd(5)
franck_mini.bk(5)
franck_mini.fd(5)
franck_mini.bk(5)
franck_mini.fd(5)
franck_mini.bk(5)

from turtle import *
from random import randint
franck_mini.shapesize(0.5,0.5,0.5)
franck_mini.rt(90)
franck_mini.fd(5)
speed(0)
                    
bgcolor('black')
      
x = 1
      
while x < 400:
      
    r = randint(0,255) #makes variables r,g,b whose value is an integer,
    g = randint(0,255) # which is between 0 and 255. It is random, and
    b = randint(0,255) # changes every time the loop runs

    colormode(255) # this is something that is irrelevant at this point
               # check the pythondocs link at the end for more info
    
    
    pencolor(r,g,b) # changes the color of the pen to the rgb coordinates
                    # obtained by the variables r, g, b changing each time
      
    fd(50 + x)
    rt(90.911)
    
    
    x = x+1 

me.clear()
franck_mini.setposition(-300,0)
me.write("Ah I'm squashed!", font=("Times New Roman", 20, "bold"))
franck_mini.write("Happy Fathers Day!", font=("Times New Roman", 50, "bold"))

exitonclick()
turtle.done()
